WebApplication2/Controllers/DisastersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Areas.Identity.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class DisastersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DisastersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Disasters
        public async Task<IActionResult> Index()
        {
              return _context.Disasters != null ? 
                          View(await _context.Disasters.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Disasters'  is null.");
        }

        // GET: Disasters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Disasters == null)
            {
                return NotFound();
            }

            var disasters = await _context.Disasters
                .FirstOrDefaultAsync(m => m.DisID == id);
            if (disasters == null)
            {
                return NotFound();
            }

            return View(disasters);
        }

        // GET: Disasters/Create
        public IActionResult Create()
        {
            var Options = new List<SelectListItem>();
            Options.Add(new SelectListItem { Value = "Clothes", Text = "Clothes" });
            Options.Add(new SelectListItem { Value = "Foods", Text = "Foods" });

            ViewBag.Options = Options;

            return View();
        }

        // POST: Disasters/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DisID,StartDate,EndDate,Location,Description,AidType")] Disasters disasters)
        {
            if (ModelState.IsValid)
            {
                _context.Add(disasters);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(disasters);
        }

        // GET: Disasters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Disasters == null)
            {
                return NotFound();
            }

            var disasters = await _context.Disasters.FindAsync(id);
            if (disasters == null)
            {
                return NotFound();
            }
            return View(disasters);
        }

        // POST: Disasters/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DisID,StartDate,EndDate,Location,Description,AidType")] Disasters disasters)
        {
            if (id != disasters.DisID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(disasters);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DisastersExists(disasters.DisID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(disasters);
        }

        // GET: Disasters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Disasters == null)
            {
                return NotFound();
            }

            var disasters = await _context.Disasters
                .FirstOrDefaultAsync(m => m.DisID == id);
            if (disasters == null)
            {
                return NotFound();
            }

            return View(disasters);
        }

        // POST: Disasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Disasters == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Disasters'  is null.");
            }
            var disasters = await _context.Disasters.FindAsync(id);
            if (disasters != null)
            {
                _context.Disasters.Remove(disasters);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DisastersExists(int id)
        {
          return (_context.Disasters?.Any(e => e.DisID == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/Controllers/GoodsDonationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Areas.Identity.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class GoodsDonationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GoodsDonationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: GoodsDonations
        public async Task<IActionResult> Index()
        {
              return _context.GoodsDonations != null ? 
                          View(await _context.GoodsDonations.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.GoodsDonations'  is null.");
        }

        // GET: GoodsDonations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.GoodsDonations == null)
            {
                return NotFound();
            }

            var goodsDonations = await _context.GoodsDonations
                .FirstOrDefaultAsync(m => m.GDonID == id);
            if (goodsDonations == null)
            {
                return NotFound();
            }

            return View(goodsDonations);
        }

        // GET: GoodsDonations/Create
        public IActionResult Create()
        {
            var categories = _context.Categories.ToList();

            var categoryOptions = categories.Select(c => new SelectListItem
            {
                Value = c.Name, 
                Text = c.Name 
            }).ToList();
            categoryOptions.Add(new SelectListItem { Value = "Clothes", Text = "Clothes" });
            categoryOptions.Add(new SelectListItem { Value = "Foods", Text = "Foods" });

            ViewBag.CategoryOptions = categoryOptions;

            return View();
        }

        // POST: GoodsDonations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GDonID,Date,NumberOfItems,Category,Description,DonorName")] GoodsDonations goodsDonations)
        {
            if (ModelState.IsValid)
            {
                if (goodsDonations.DonorName == "A")
                {
                    goodsDonations.DonorName = "Anonymous";
                }

                _context.Add(goodsDonations);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var categories = _context.Categories.ToList();
            var categoryOptions = categories.Select(c => new SelectListItem
            {
                Value = c.Name,
                Text = c.Name
            }).ToList();
            ViewBag.CategoryOptions = categoryOptions;

            return View(goodsDonations);
        }

        // GET: GoodsDonations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.GoodsDonations == null)
            {
                return NotFound();
            }

            var goodsDonations = await _context.GoodsDonations.FindAsync(id);
            if (goodsDonations == null)
            {
                return NotFound();
            }
            return View(goodsDonations);
        }

        // POST: GoodsDonations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GDonID,Date,NumberOfItems,Category,Description,DonorName")] GoodsDonations goodsDonations)
        {
            if (id != goodsDonations.GDonID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(goodsDonations);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GoodsDonationsExists(goodsDonations.GDonID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(goodsDonations);
        }

        // GET: GoodsDonations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.GoodsDonations == null)
            {
                return NotFound();
            }

            var goodsDonations = await _context.GoodsDonations
                .FirstOrDefaultAsync(m => m.GDonID == id);
            if (goodsDonations == null)
            {
                return NotFound();
            }

            return View(goodsDonations);
        }

        // POST: GoodsDonations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.GoodsDonations == null)
            {
                return Problem("Entity set 'ApplicationDbContext.GoodsDonations'  is null.");
            }
            var goodsDonations = await _context.GoodsDonations.FindAsync(id);
            if (goodsDonations != null)
            {
                _context.GoodsDonations.Remove(goodsDonations);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GoodsDonationsExists(int id)
        {
          return (_context.GoodsDonations?.Any(e => e.GDonID == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/Controllers/MonetaryDonationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Areas.Identity.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class MonetaryDonationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MonetaryDonationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MonetaryDonations
        public async Task<IActionResult> Index()
        {
              return _context.MonetaryDonations != null ? 
                          View(await _context.MonetaryDonations.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.MonetaryDonations'  is null.");
        }

        // GET: MonetaryDonations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MonetaryDonations == null)
            {
                return NotFound();
            }

            var monetaryDonations = await _context.MonetaryDonations
                .FirstOrDefaultAsync(m => m.MDonID == id);
            if (monetaryDonations == null)
            {
                return NotFound();
            }

            return View(monetaryDonations);
        }

        // GET: MonetaryDonations/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MonetaryDonations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MDonID,Date,Amount,DonorName")] MonetaryDonations monetaryDonations)
        {
            if (ModelState.IsValid)
            {
                if (monetaryDonations.DonorName == "A")
                {
                    monetaryDonations.DonorName = "Anonymous";
                }

                _context.Add(monetaryDonations);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(monetaryDonations);
        }

        // GET: MonetaryDonations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MonetaryDonations == null)
            {
                return NotFound();
            }

            var monetaryDonations = await _context.MonetaryDonations.FindAsync(id);
            if (monetaryDonations == null)
            {
                return NotFound();
            }
            return View(monetaryDonations);
        }

        // POST: MonetaryDonations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MDonID,Date,Amount,DonorName")] MonetaryDonations monetaryDonations)
        {
            if (id != monetaryDonations.MDonID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(monetaryDonations);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MonetaryDonationsExists(monetaryDonations.MDonID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(monetaryDonations);
        }

        // GET: MonetaryDonations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MonetaryDonations == null)
            {
                return NotFound();
            }

            var monetaryDonations = await _context.MonetaryDonations
                .FirstOrDefaultAsync(m => m.MDonID == id);
            if (monetaryDonations == null)
            {
                return NotFound();
            }

            return View(monetaryDonations);
        }

        // POST: MonetaryDonations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MonetaryDonations == null)
            {
                return Problem("Entity set 'ApplicationDbContext.MonetaryDonations'  is null.");
            }
            var monetaryDonations = await _context.MonetaryDonations.FindAsync(id);
            if (monetaryDonations != null)
            {
                _context.MonetaryDonations.Remove(monetaryDonations);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MonetaryDonationsExists(int id)
        {
          return (_context.MonetaryDonations?.Any(e => e.MDonID == id)).GetValueOrDefault();
        }
    }
}

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />

    <style>
        .navbar-brand,
        .nav-link.custom-text-color {
            color: #ff6f00 !important;
            position: relative;
            padding-left: 20px;
        }

            .navbar-brand::after {
                content: "";
                display: block;
                width: 100%;
                height: 2px;
                background-color: #ff6f00;
                position: absolute;
                bottom: -10px;
                left: 0;
            }

        .navbar-nav .nav-link.text-dark.custom-text-color {
            color: #ff6f00 !important;
            padding-left: 20px; 
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-purple border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    Disaster Alleviation Foundation
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark custom-text-color" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark custom-text-color" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark custom-text-color" asp-area="" asp-controller="MonetaryDonations" asp-action="Index">Monetary Donations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark custom-text-color" asp-area="" asp-controller="GoodsDonations" asp-action="Index">Goods Donations</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark custom-text-color" asp-area="" asp-controller="Disasters" asp-action="Index">Disasters</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Disaster Management
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>